export const servicePackages = [
  {
    id: "audit",
    title: "Modernization Audit",
    timeframe: "5-7 days",
    description: "A focused review of an existing app, workflow, or platform before committing to a larger rebuild.",
    outcomes: [
      "Risk and bottleneck map",
      "Architecture and integration notes",
      "Prioritized delivery plan",
      "Budget and sprint estimate",
    ],
    bestFor: "Teams unsure whether to repair, rebuild, or integrate AI into an existing system.",
  },
  {
    id: "rescue",
    title: "Rescue Sprint",
    timeframe: "2-4 weeks",
    description: "Stabilize an unfinished or unreliable web app, SaaS platform, API layer, or deployment setup.",
    outcomes: [
      "Production fixes and deployment cleanup",
      "Frontend/backend issue triage",
      "Database and API reliability work",
      "Handover notes for the next phase",
    ],
    bestFor: "Founders, agencies, and teams with a product that is stuck near delivery.",
  },
  {
    id: "ai-pilot",
    title: "AI Integration Pilot",
    timeframe: "2-6 weeks",
    description: "Build a narrow AI workflow around documents, support knowledge, reports, or internal operations.",
    outcomes: [
      "RAG/CAG proof of concept",
      "Data ingestion and retrieval flow",
      "Human-review guardrails",
      "Pilot metrics and rollout plan",
    ],
    bestFor: "Companies that want practical AI value without a long research project.",
  },
];

export const proofDemos = [
  {
    id: "ai-document-assistant",
    title: "AI Document Assistant",
    signal: "RAG / CAG / document intelligence",
    description: "A small public proof concept for asking grounded questions over business documents, notes, PDFs, and project knowledge.",
    workflow: ["Upload or connect documents", "Chunk and index context", "Ask questions with citations", "Review answers before action"],
    route: "#lead-capture",
  },
  {
    id: "legacy-audit-dashboard",
    title: "Legacy App Audit Dashboard",
    signal: "Rescue sprint / modernization review",
    description: "A lightweight diagnostic board for scoring app risk, missing operations, deployment health, and modernization priority.",
    workflow: ["Collect system facts", "Score risk and value", "Map quick wins", "Plan the next sprint"],
    route: "#lead-capture",
  },
];

export const regionCampaigns = {
  dach: {
    path: "/dach-modernization",
    label: "DACH",
    defaultLocale: "de",
    locales: {
      de: {
        label: "DE",
        title: "DACH Business Modernisierung",
        kicker: "Oesterreich, Deutschland, Schweiz",
        headline: "Zuverlaessige Senior-Umsetzung fuer Modernisierung im DACH-Raum",
        description: "Fuer Teams, die stabile Entwicklung, klare Dokumentation und pragmatische Modernisierung von Legacy-Systemen, Portalen, APIs und KI-gestuetzten Workflows brauchen.",
        angle: "Zuerst auditieren, dann kontrollierte Verbesserungen liefern, ohne den laufenden Betrieb zu stoeren.",
        proof: ["Finance- und Banking-Systeme", "DACH-Recruiting-Plattformen", "Automotive- und Commerce-Projekte"],
        primaryCta: "Mit kurzer Scope starten",
        secondaryCta: "Gesamtes Portfolio ansehen",
        regionalKicker: "Regionaler Fokus",
        packagesKicker: "Empfohlene Startpunkte",
        packagesTitle: "Pakete fuer DACH-Gespraeche",
      },
      en: {
        label: "EN",
        title: "DACH Business Modernization",
        kicker: "Austria, Germany, Switzerland",
        headline: "Reliable senior delivery for DACH modernization work",
        description: "For teams that need stable engineering, clear documentation, and pragmatic modernization across legacy systems, portals, APIs, and AI-enabled workflows.",
        angle: "Audit first, then deliver controlled improvements without interrupting business operations.",
        proof: ["Finance and banking systems", "DACH recruitment platforms", "Automotive and commerce work"],
        primaryCta: "Start with a short scope",
        secondaryCta: "View full portfolio",
        regionalKicker: "Regional angle",
        packagesKicker: "Recommended starting points",
        packagesTitle: "Packages for DACH conversations",
      },
    },
  },
  gcc: {
    path: "/gcc-ai-integration",
    label: "GCC",
    defaultLocale: "en",
    locales: {
      en: {
        label: "EN",
        title: "GCC AI Integration",
        kicker: "Dubai, Saudi Arabia, Gulf teams",
        headline: "AI and workflow platforms for business operations",
        description: "For companies that do not just need another website, but need connected business systems, dashboards, internal tools, and practical AI support.",
        angle: "Start with one measurable workflow: documents, support, reporting, customer operations, or internal approvals.",
        proof: ["SaaS platforms", "E-commerce integrations", "AI document workflows"],
        primaryCta: "Start with a short scope",
        secondaryCta: "View full portfolio",
        regionalKicker: "Regional angle",
        packagesKicker: "Recommended starting points",
        packagesTitle: "Packages for GCC conversations",
      },
      ar: {
        label: "AR",
        title: "تكامل الذكاء الاصطناعي لمنطقة الخليج",
        kicker: "دبي، السعودية، وفرق الخليج",
        headline: "منصات ذكاء اصطناعي وسير عمل لعمليات الأعمال",
        description: "للشركات التي لا تحتاج فقط إلى موقع جديد، بل تحتاج إلى أنظمة أعمال مترابطة ولوحات متابعة وأدوات داخلية ودعم عملي بالذكاء الاصطناعي.",
        angle: "ابدأ بسير عمل واحد يمكن قياسه: المستندات، الدعم، التقارير، عمليات العملاء، أو الموافقات الداخلية.",
        proof: ["منصات SaaS", "تكاملات التجارة الإلكترونية", "سير عمل المستندات بالذكاء الاصطناعي"],
        primaryCta: "ابدأ بنطاق عمل قصير",
        secondaryCta: "عرض كامل للأعمال",
        regionalKicker: "زاوية إقليمية",
        packagesKicker: "نقاط بداية مقترحة",
        packagesTitle: "باقات مناسبة لمحادثات الخليج",
        dir: "rtl",
      },
    },
  },
  uk: {
    path: "/uk-saas-rescue",
    label: "UK",
    defaultLocale: "en",
    locales: {
      en: {
        label: "EN",
        title: "UK SaaS Rescue Sprint",
        kicker: "Startups, agencies, SaaS teams",
        headline: "Senior rescue support for unfinished SaaS and web apps",
        description: "For teams that need direct ownership, faster technical decisions, and a clear path from unstable build to shippable product.",
        angle: "Use a short rescue sprint to reduce risk before expanding scope.",
        proof: ["React and SaaS dashboards", "Node/Nest/Laravel APIs", "Production deployment support"],
        primaryCta: "Start with a short scope",
        secondaryCta: "View full portfolio",
        regionalKicker: "Regional angle",
        packagesKicker: "Recommended starting points",
        packagesTitle: "Packages for UK conversations",
      },
    },
  },
  asia: {
    path: "/asia-ai-integration",
    label: "Asia",
    defaultLocale: "en",
    locales: {
      en: {
        label: "EN",
        title: "Asia AI Integration",
        kicker: "Asia-Pacific and remote teams",
        headline: "English-first AI and platform delivery for Asia-facing teams",
        description: "For companies that need business workflow modernization, system integrations, dashboards, and practical AI pilots without assuming one local language across the region.",
        angle: "Keep the first page in English, then localize later for the markets that actually respond.",
        proof: ["AI document workflows", "SaaS and internal dashboards", "API and e-commerce integrations"],
        primaryCta: "Start with a short scope",
        secondaryCta: "View full portfolio",
        regionalKicker: "Regional angle",
        packagesKicker: "Recommended starting points",
        packagesTitle: "Packages for Asia conversations",
      },
    },
  },
};
